name: ramadan_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^6.0.5
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  get_storage: ^2.1.1
  google_fonts: any
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logger: any
  retrofit: ^4.0.1
  shimmer: ^3.0.0
  smooth_compass: ^2.0.17
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  auto_route_generator: ^6.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/images/
    - assets/images/categories/
    - assets/images/titles/
    - assets/images/ramadan_time/
    - assets/images/qiable_finder/
    - assets/images/prayer/
    - assets/icons/
    - assets/images/onboarding/
